apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/kshitijcode/kalypso-sharmaks-v14-control-plane
  branch: main
  path: .
  commit: 0803f29cc6dacbc505b2b30adef485c3731b4f07
